name: newu_breathe
description: "A beautiful breathing exercise app with mobile-first design and web support"

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  google_fonts: ^8.0.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/light/
    - assets/images/dark/
    - assets/images/common/
    - assets/lottie/
    - assets/audio/
